mqtt:
  broker: "tcp://localhost:1883"
  client_id: "v2g-dispatcher"
  username: ""
  password: ""
  ack_topic: "vehicle/+/ack"
  use_tls: false
dispatch:
  ack_timeout_seconds: 5
  lp_first:
    "0": true # FCR
  enable_soc_constraints: true
  min_soc: 0.1
  safe_discharge_floor: 0.1
  segments:
    commuter:
      dispatcher_type: "heuristic"
    captive_fleet:
      dispatcher_type: "lp"
      fallback: true
    opportunistic_charger:
      dispatcher_type: "heuristic"
      fallback: true
metrics:
  sinks:
    - type: "prometheus"
      conf:
        prometheus_port: ":2112"
  # additional sinks can be listed here
  emission_factor: 50 # gCO2 per kWh
logging:
  backend: "jsonl" # or 'sqlite'
  path: "dispatch.log"
  max_size_mb: 10
  max_backups: 5
  max_age_days: 7
rte:
  mode: "mock" # or 'client'
  mock:
    address: ":8081"
  client:
    api_url: "https://api.rte.com"
    client_id: ""
    client_secret: ""
    token_url: "https://auth.rte.com/token"
    poll_interval_seconds: 60
