mqtt:
  broker: "tcp://localhost:1883"
  client_id: "v2g-dispatcher"
  username: ""
  password: ""
  ack_topic: "vehicle/+/ack"
  use_tls: false
dispatch:
  ack_timeout_seconds: 5
  lp_first:
    "0": true # FCR
  segments:
    commuter:
      dispatcher_type: "heuristic"
    captive_fleet:
      dispatcher_type: "lp"
      fallback: true
    opportunistic_charger:
      dispatcher_type: "heuristic"
      fallback: true
metrics:
  prometheus_enabled: true
  prometheus_port: ":2112"
  influx_enabled: true
  influx_url: "http://influxdb:8086"
  influx_token: "secret"
  influx_org: "my-org"
  influx_bucket: "v2g"
rte:
  mode: "mock" # or 'client'
  mock:
    address: ":8081"
  client:
    api_url: "https://api.rte.com"
    client_id: ""
    client_secret: ""
    token_url: "https://auth.rte.com/token"
    poll_interval_seconds: 60
